### ISSUE TITLE
Startup location & terrain collision

### ISSUE THREAD

**Issue by hassanayoub1985** [melowntech/VtsJetFighter#1]
Hello,
Impressive work.
I run it on 2019.4.2 and it works smoothly :)
I am planning to use it as a core for my demo about corona virus.
How to change the startup location of the map?
and can the terrain be collided?
Thanks

**Comment by malytomas** [comment]
Use 'Vts Map Make Local' script to change the starting coordinates.
Use 'Collider Probe' to generate colliders.
See https://github.com/melowntech/vts-browser-unity-plugin/wiki for more information.
